# Generated by Django 4.0.5 on 2022-07-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_student_admission_number'),
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedbackresponse',
            unique_together={('student', 'feedback')},
        ),
    ]
